export enum POPUP_ID {
  SAMPLE = 'SAMPLE',
  ADD_LP = 'ADD_LP',

  SWAP_SELECT_TOKEN_FROM = 'SWAP_SELECT_TOKEN_FROM',
  SWAP_SELECT_TOKEN_TO = 'SWAP_SELECT_TOKEN_TO',

  SWAP_PREVICE = 'SWAP_PREVICE',
  SWAP_SUCCESS = 'SWAP_SUCCESS',
}
