export enum POPUP_ID {
  SAMPLE = 'SAMPLE',
  ADD_LP = 'ADD_LP',
  WITHDRAW_LP = 'WITHDRAW_LP',

  SWAP_SELECT_TOKEN_FROM = 'SWAP_SELECT_TOKEN_FROM',
  SWAP_SELECT_TOKEN_TO = 'SWAP_SELECT_TOKEN_TO',

  SWAP = 'SWAP',
}
