name: Deploy on Comment

on:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Mantle Comment
        id: check_mantle_comment
        run: |
          # Extract the comment body from the event payload
          comment_body=$(jq -r .comment.body "$GITHUB_EVENT_PATH")
          
          # Check if the comment contains "/deploy mantle"
          if [[ $comment_body == *"/deploy mantle"* ]]; then
            echo "::set-output name=deploy::true"
          fi

      - name: Deploy Mantle
        if: steps.check_mantle_comment.outputs.deploy == 'true'
        uses: ./.github/workflows/deploy-mantle.yml

      - name: Check Linea Comment
        id: check_linea_comment
        run: |
          # Extract the comment body from the event payload
          comment_body=$(jq -r .comment.body "$GITHUB_EVENT_PATH")
          
          # Check if the comment contains "/deploy linea"
          if [[ $comment_body == *"/deploy linea"* ]]; then
            echo "::set-output name=deploy::true"
          fi

      - name: Deploy Linea
        if: steps.check_linea_comment.outputs.deploy == 'true'
        uses: ./.github/workflows/deploy-linea.yml
